### ISSUE TITLE
PCB Fabrication Information

### ISSUE THREAD

**Issue by alevan10** [sb-ocr/pi-terminal#2]
I've tried sending the zip files here, as well as the project you have uploaded to PCBWay to try and get these fabricated by them. However, as a someone new to PCB fabrication, I don't know any of the correct settings, nor can I edit the gerber files myself with any confidence. PCBWay replied back that, specifically, the information in the Front Panel PCB don't make it clear what they should do with the three openings for the LCDs. Do you have additional information, or updated files that you might be able to post here, or any guidance on how best to get these produced. Everything else you have has worked great!

**Comment by sb-ocr** [comment]
Layers: 2
Material: FR4
Thickness: 1.6mm 
Solder Mask: Black (or choose the color you want)

If you're ordering from PCBWay, you can keep the rest of the options as default.

I'm not sure what LCDs you are referring to, but the '3 slots' on the front panel are diffusion for the LEDs. The board has the copper and solder mask removed from those spots on both sides, only FR4 is exposed and let the light shines through (see the image below).

Best of luck!

![Screenshot 2023-10-15 at 3 54 02 PM](https://github.com/sb-ocr/pi-terminal/assets/99417980/a5f0bd55-b388-4ff2-b97f-20c829f37517)

**Comment by alevan10** [comment]
lol, I meant LEDs. Thank you very much! I'm really looking forward to working through this project!
